apiVersion: v1
kind: Pod
metadata:
  name: img-captioning
spec:
  containers:
  - name: mypod
    image: pytorch/pytorch
    resources:
      limits:
        memory: 10Gi
        cpu: 4
        nvidia.com/a100: 1
      requests:
        memory: 8Gi
        cpu: 3
        nvidia.com/a100: 1
    volumeMounts:
    - mountPath: /workspace
      name: workspace
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: image-captioning-vol